//CORE_REFERENCE_IMPORTS
//CORE_REFERENCE_IMPORT-updateProposalMembersById-DMOPS_ID_proposals___EN_0xcbgpnumf__updateProposalMembersById
import { updateProposalMembersById as DMOPS_ID_proposals___EN_0xcbgpnumf__updateProposalMembersById } from './dm-services/proposals/proposal_members/updateProposalMembersById';
//CORE_REFERENCE_IMPORT-updateAllProposalMemberss-DMOPS_ID_proposals___EN_0xcbgpnumf__updateAllProposalMemberss
import { updateAllProposalMemberss as DMOPS_ID_proposals___EN_0xcbgpnumf__updateAllProposalMemberss } from './dm-services/proposals/proposal_members/updateAllProposalMemberss';
//CORE_REFERENCE_IMPORT-findProposalMembersById-DMOPS_ID_proposals___EN_0xcbgpnumf__findProposalMembersById
import { findProposalMembersById as DMOPS_ID_proposals___EN_0xcbgpnumf__findProposalMembersById } from './dm-services/proposals/proposal_members/findProposalMembersById';
//CORE_REFERENCE_IMPORT-findAllProposalMemberss-DMOPS_ID_proposals___EN_0xcbgpnumf__findAllProposalMemberss
import { findAllProposalMemberss as DMOPS_ID_proposals___EN_0xcbgpnumf__findAllProposalMemberss } from './dm-services/proposals/proposal_members/findAllProposalMemberss';
//CORE_REFERENCE_IMPORT-deleteProposalMembersById-DMOPS_ID_proposals___EN_0xcbgpnumf__deleteProposalMembersById
import { deleteProposalMembersById as DMOPS_ID_proposals___EN_0xcbgpnumf__deleteProposalMembersById } from './dm-services/proposals/proposal_members/deleteProposalMembersById';
//CORE_REFERENCE_IMPORT-deleteAllProposalMemberss-DMOPS_ID_proposals___EN_0xcbgpnumf__deleteAllProposalMemberss
import { deleteAllProposalMemberss as DMOPS_ID_proposals___EN_0xcbgpnumf__deleteAllProposalMemberss } from './dm-services/proposals/proposal_members/deleteAllProposalMemberss';
//CORE_REFERENCE_IMPORT-createAllProposalMembers-DMOPS_ID_proposals___EN_0xcbgpnumf__createAllProposalMembers
import { createAllProposalMembers as DMOPS_ID_proposals___EN_0xcbgpnumf__createAllProposalMembers } from './dm-services/proposals/proposal_members/createAllProposalMembers';
//CORE_REFERENCE_IMPORT-createProposalMembers-DMOPS_ID_proposals___EN_0xcbgpnumf__createProposalMembers
import { createProposalMembers as DMOPS_ID_proposals___EN_0xcbgpnumf__createProposalMembers } from './dm-services/proposals/proposal_members/createProposalMembers';
//CORE_REFERENCE_IMPORT-updateProposalsById-DMOPS_ID_proposals___EN_hll0abjopf__updateProposalsById
import { updateProposalsById as DMOPS_ID_proposals___EN_hll0abjopf__updateProposalsById } from './dm-services/proposals/proposals/updateProposalsById';
//CORE_REFERENCE_IMPORT-updateAllProposalss-DMOPS_ID_proposals___EN_hll0abjopf__updateAllProposalss
import { updateAllProposalss as DMOPS_ID_proposals___EN_hll0abjopf__updateAllProposalss } from './dm-services/proposals/proposals/updateAllProposalss';
//CORE_REFERENCE_IMPORT-findProposalsById-DMOPS_ID_proposals___EN_hll0abjopf__findProposalsById
import { findProposalsById as DMOPS_ID_proposals___EN_hll0abjopf__findProposalsById } from './dm-services/proposals/proposals/findProposalsById';
//CORE_REFERENCE_IMPORT-findAllProposalss-DMOPS_ID_proposals___EN_hll0abjopf__findAllProposalss
import { findAllProposalss as DMOPS_ID_proposals___EN_hll0abjopf__findAllProposalss } from './dm-services/proposals/proposals/findAllProposalss';
//CORE_REFERENCE_IMPORT-deleteProposalsById-DMOPS_ID_proposals___EN_hll0abjopf__deleteProposalsById
import { deleteProposalsById as DMOPS_ID_proposals___EN_hll0abjopf__deleteProposalsById } from './dm-services/proposals/proposals/deleteProposalsById';
//CORE_REFERENCE_IMPORT-deleteAllProposalss-DMOPS_ID_proposals___EN_hll0abjopf__deleteAllProposalss
import { deleteAllProposalss as DMOPS_ID_proposals___EN_hll0abjopf__deleteAllProposalss } from './dm-services/proposals/proposals/deleteAllProposalss';
//CORE_REFERENCE_IMPORT-createAllProposals-DMOPS_ID_proposals___EN_hll0abjopf__createAllProposals
import { createAllProposals as DMOPS_ID_proposals___EN_hll0abjopf__createAllProposals } from './dm-services/proposals/proposals/createAllProposals';
//CORE_REFERENCE_IMPORT-createProposals-DMOPS_ID_proposals___EN_hll0abjopf__createProposals
import { createProposals as DMOPS_ID_proposals___EN_hll0abjopf__createProposals } from './dm-services/proposals/proposals/createProposals';

export const DmRoutes = [
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-updateProposalMembersById-DMOPS_ID_proposals___EN_0xcbgpnumf__updateProposalMembersById
  DMOPS_ID_proposals___EN_0xcbgpnumf__updateProposalMembersById,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-updateAllProposalMemberss-DMOPS_ID_proposals___EN_0xcbgpnumf__updateAllProposalMemberss
  DMOPS_ID_proposals___EN_0xcbgpnumf__updateAllProposalMemberss,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-findProposalMembersById-DMOPS_ID_proposals___EN_0xcbgpnumf__findProposalMembersById
  DMOPS_ID_proposals___EN_0xcbgpnumf__findProposalMembersById,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-findAllProposalMemberss-DMOPS_ID_proposals___EN_0xcbgpnumf__findAllProposalMemberss
  DMOPS_ID_proposals___EN_0xcbgpnumf__findAllProposalMemberss,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-deleteProposalMembersById-DMOPS_ID_proposals___EN_0xcbgpnumf__deleteProposalMembersById
  DMOPS_ID_proposals___EN_0xcbgpnumf__deleteProposalMembersById,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-deleteAllProposalMemberss-DMOPS_ID_proposals___EN_0xcbgpnumf__deleteAllProposalMemberss
  DMOPS_ID_proposals___EN_0xcbgpnumf__deleteAllProposalMemberss,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-createAllProposalMembers-DMOPS_ID_proposals___EN_0xcbgpnumf__createAllProposalMembers
  DMOPS_ID_proposals___EN_0xcbgpnumf__createAllProposalMembers,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-createProposalMembers-DMOPS_ID_proposals___EN_0xcbgpnumf__createProposalMembers
  DMOPS_ID_proposals___EN_0xcbgpnumf__createProposalMembers,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-updateProposalsById-DMOPS_ID_proposals___EN_hll0abjopf__updateProposalsById
  DMOPS_ID_proposals___EN_hll0abjopf__updateProposalsById,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-updateAllProposalss-DMOPS_ID_proposals___EN_hll0abjopf__updateAllProposalss
  DMOPS_ID_proposals___EN_hll0abjopf__updateAllProposalss,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-findProposalsById-DMOPS_ID_proposals___EN_hll0abjopf__findProposalsById
  DMOPS_ID_proposals___EN_hll0abjopf__findProposalsById,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-findAllProposalss-DMOPS_ID_proposals___EN_hll0abjopf__findAllProposalss
  DMOPS_ID_proposals___EN_hll0abjopf__findAllProposalss,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-deleteProposalsById-DMOPS_ID_proposals___EN_hll0abjopf__deleteProposalsById
  DMOPS_ID_proposals___EN_hll0abjopf__deleteProposalsById,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-deleteAllProposalss-DMOPS_ID_proposals___EN_hll0abjopf__deleteAllProposalss
  DMOPS_ID_proposals___EN_hll0abjopf__deleteAllProposalss,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-createAllProposals-DMOPS_ID_proposals___EN_hll0abjopf__createAllProposals
  DMOPS_ID_proposals___EN_hll0abjopf__createAllProposals,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-createProposals-DMOPS_ID_proposals___EN_hll0abjopf__createProposals
  DMOPS_ID_proposals___EN_hll0abjopf__createProposals,
];
